# Generated by Django 6.0.5 on 2026-05-31 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(default='Identifier', max_length=128, null=True, verbose_name='Identifiant expérience')),
                ('well', models.CharField(choices=[], default='A1', help_text='Nom du puit', max_length=8, null=True, verbose_name='Puit')),
                ('description', models.TextField(blank=True, default='-', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('px_per_mm', models.FloatField(default=26.25, help_text='Facteur de calibration optique', verbose_name='Pixels par mm')),
                ('fps', models.FloatField(default=5.0, help_text='Image de capture en img/s', verbose_name='FPS de capture')),
                ('well_radius_mm', models.FloatField(default=8.0, help_text='En mm', verbose_name='Rayon du puits')),
                ('thresh_immobile', models.FloatField(default=0.2, verbose_name='Seuil Immobile (mm/s)')),
                ('thresh_mobile', models.FloatField(default=1.5, verbose_name='Seuil Mobile (mm/s)')),
                ('tube_axis', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=10, verbose_name='Axe du tube')),
                ('min_area_px', models.IntegerField(default=20, verbose_name='Surface min détection (px²)')),
                ('max_area_ratio', models.FloatField(default=0.1, help_text='Ratio de la surface du puits, ex: 0.10 pour 10%', verbose_name='Surface max contour (fraction de la frame)')),
                ('planarian_count', models.IntegerField(default=1, verbose_name='Nombre de planaires')),
                ('merge_kernel_size', models.PositiveIntegerField(default=15, help_text='taille du kernel elliptique de fusion des fragments (px). Augmenter si fragments résiduels', verbose_name='Taille du kernel')),
                ('min_contour_dist_px', models.PositiveIntegerField(default=40, help_text='Distance min entre deux contours pour les considérer comme individus distincts. Défaut : 40px. Augmenter si IDs multiples persistent', verbose_name='Distance <contour>')),
                ('thigmotaxis_wall_dist_mm', models.FloatField(default=1.0, verbose_name='Distance paroi thigmotactisme (mm)')),
                ('photo_mode', models.CharField(choices=[('none', 'Désactivé'), ('fixed', 'Source fixe'), ('sine', 'Source sinusoïdale'), ('radial', 'Gradient radial')], default='none', max_length=10, verbose_name='Mode phototactisme')),
                ('photo_strength', models.FloatField(default=0.0, verbose_name='Intensité phototactisme')),
                ('photo_x', models.FloatField(default=0.5, verbose_name='Source lumière X (0-1)')),
                ('photo_y', models.FloatField(default=0.5, verbose_name='Source lumière Y (0-1)')),
                ('chemo_strength', models.FloatField(default=0.0, verbose_name='Intensité chimiotactisme')),
                ('chemo_x', models.FloatField(default=0.5, verbose_name='Nourriture X (0-1)')),
                ('chemo_y', models.FloatField(default=0.5, verbose_name='Nourriture Y (0-1)')),
                ('chemo_radius_mm', models.FloatField(default=2.0, verbose_name='Rayon nourriture (mm)')),
                ('avoid_radius_mm', models.FloatField(default=3.0, verbose_name='Rayon évitement (mm)')),
                ('aggreg_radius_mm', models.FloatField(default=6.0, verbose_name='Rayon agrégation (mm)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': "Configuration d'une expérience",
                'verbose_name_plural': 'Configurations des expériences',
                'ordering': ['-created_at'],
            },
        ),
    ]
