# Generated by Django 6.0.5 on 2026-05-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planarian', '0001_initial'),
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentconfig',
            name='experiment_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.experiment', verbose_name='Expérience'),
        ),
        migrations.AlterUniqueTogether(
            name='experimentconfig',
            unique_together={('experiment_key', 'well')},
        ),
    ]
