# Generated by Django 6.0.5 on 2026-05-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiwell',
            name='crop_radius',
        ),
    ]
