# Generated by Django 6.0.5 on 2026-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_multiwell_crop_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiwell',
            name='crop_radius',
            field=models.PositiveSmallIntegerField(default=500, help_text='Rayon en pixels pour recadrer les images en px', verbose_name='Rayon de découpe recadrage'),
        ),
    ]
