# Generated by Django 6.0.5 on 2026-06-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_add_videoplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiwell',
            options={'ordering': ['label', 'order'], 'verbose_name': 'Multi-puits', 'verbose_name_plural': 'Multi-puits'},
        ),
        migrations.AddField(
            model_name='multiwell',
            name='capture_video',
            field=models.BooleanField(default=False, help_text='Ce multi-puit servira pour la capture vidéo', verbose_name='Capture vidéo'),
        ),
    ]
