# Generated by Django 6.0.5 on 2026-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_multiwell_options_multiwell_capture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiwell',
            name='capture_video',
            field=models.BooleanField(default=False, help_text='Ce multi-puit servira pour la capture vidéo', verbose_name='Vidéo'),
        ),
        migrations.AlterField(
            model_name='multiwell',
            name='default',
            field=models.BooleanField(default=False, help_text='Multi-puit par défaut', verbose_name='Défaut'),
        ),
    ]
