# Generated by Django 6.0.5 on 2026-06-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_alter_multiwell_capture_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoplate',
            name='px_per_mm',
            field=models.FloatField(default=15.0, help_text='Facteur pixels/mm dans la vidéo plaque. À calibrer selon la résolution de la caméra plaque.', verbose_name='Pixels par mm (vidéo plaque)'),
        ),
    ]
