# Generated by Django 6.0.5 on 2026-06-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_add_videoplate_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoplate',
            name='x_origin_mm',
            field=models.FloatField(default=0.0, help_text='Position CNC X correspondant au bord gauche de la vidéo plaque (mm). Défaut 0.', verbose_name='Origine X (mm)'),
        ),
        migrations.AlterField(
            model_name='videoplate',
            name='y_origin_mm',
            field=models.FloatField(default=0.0, help_text='Position CNC Y correspondant au bord haut de la vidéo plaque (mm). Défaut 0.', verbose_name='Origine Y (mm)'),
        ),
    ]
