# Generated by Django 6.0.5 on 2026-07-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_alter_videoplate_x_origin_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiWellPositionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Clé courte, ex: HG_96', max_length=8, unique=True, verbose_name='Code')),
                ('label', models.CharField(help_text='Libellé affiché dans les menus', max_length=100, verbose_name='Libellé')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Position multi-puits (référentiel)',
                'verbose_name_plural': 'Positions multi-puits (référentiel)',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='configuration',
            name='calibration_default_multiwell',
            field=models.CharField(default='HG', help_text='Position du multi-puits de calibration par défaut', max_length=8, verbose_name='Multi-puits de calibration par défaut'),
        ),
        migrations.AlterField(
            model_name='multiwell',
            name='position',
            field=models.CharField(help_text='Position du multi-puits sur la table', max_length=8, null=True, unique=True, verbose_name='Position'),
        ),
    ]
