# Generated by Django 6.0.5 on 2026-07-22 06:08

from django.db import migrations

# Snapshot de l'ancienne liste Python MULTIWELL_POSITION (scanner/models.py),
# reprise ici telle quelle — les migrations ne doivent pas dépendre de code
# applicatif susceptible de changer.
SEED = [
    ('HG',    "MP 4x6: HG-Haut gauche",   0),
    ('HD',    "MP 4x6: HD-Haut droit",    1),
    ('BG',    "MP 4x6: BG-Bas gauche",    2),
    ('BD',    "MP 4x6: BD-Bas droit",     3),
    ('HG_6',  "MP 2x3: HG-Haut gauche",   4),
    ('HD_6',  "MP 2x3: HD-Haut droit",    5),
    ('BG_6',  "MP 2x3: BG-Bas gauche",    6),
    ('BD_6',  "MP 2x3: BD-Bas droit",     7),
    ('HG_12', "MP 3x4: HG-Haut gauche",   8),
    ('HD_12', "MP 3x4: HD-Haut droit",    9),
    ('BG_12', "MP 3x4: BG-Bas gauche",   10),
    ('BD_12', "MP 3x4: BD-Bas droit",    11),
    ('HG_48', "MP 6x8: HG-Haut gauche",  12),
    ('HD_48', "MP 6x8: HD-Haut droit",   13),
    ('BG_48', "MP 6x8: BG-Bas gauche",   14),
    ('BD_48', "MP 6x8: BD-Bas droit",    15),
    ('HG_96', "MP 8x12: HG-Haut gauche", 16),
    ('HD_96', "MP 8x12: HD-Haut droit",  17),
    ('BG_96', "MP 8x12: BG-Bas gauche",  18),
    ('BD_96', "MP 8x12: BD-Bas droit",   19),
]


def seed_choices(apps, schema_editor):
    MultiWellPositionChoice = apps.get_model('scanner', 'MultiWellPositionChoice')
    for code, label, order in SEED:
        MultiWellPositionChoice.objects.update_or_create(
            code=code, defaults={'label': label, 'order': order}
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_multiwellpositionchoice_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_choices, noop),
    ]
