# Generated by Django 6.0.5 on 2026-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_seed_multiwell_position_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiwell',
            name='row_order',
        ),
        migrations.AlterField(
            model_name='multiwell',
            name='row_def',
            field=models.CharField(default='A,B,C,D,E,F,G,H', help_text='Définition des lignes', max_length=16, null=True, verbose_name='Définition'),
        ),
    ]
