# Generated by Django 6.0.5 on 2026-07-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_remove_multiwell_row_order_alter_multiwell_row_def'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiwell',
            name='px_per_mm',
            field=models.FloatField(default=11.5, help_text='Facteur de calibration optique par defaut', verbose_name='Pixels par mm'),
        ),
        migrations.AlterField(
            model_name='wellposition',
            name='px_per_mm',
            field=models.FloatField(default=11.5, help_text='Facteur de calibration optique', verbose_name='Pixels par mm'),
        ),
    ]
